external-dns:
  image:
    registry: registry.k8s.io
    repository: external-dns/external-dns
    tag: v0.14.0

  # restrict to namespace
  # namespace: external-dns 

  #zoneNameFilters:
  #  - dome-marketplace-dev.org

  provider: webhook

  extraArgs:
    webhook-provider-url: http://localhost:8888

  sidecars:
    - name: ionos-webhook
      image: ghcr.io/ionos-cloud/external-dns-ionos-webhook:v0.6.0
      ports:
        - containerPort: 8888
          name: http
      livenessProbe:
        httpGet:
          path: /health
          port: http
        initialDelaySeconds: 10
        timeoutSeconds: 5
      readinessProbe:
        httpGet:
          path: /health
          port: http
        initialDelaySeconds: 10
        timeoutSeconds: 5
      env:
        #- name: REGEXP_DOMAIN_FILTER
        #  value: ".*.dome-marketplace-dev.org"
        #- name: EXCLUDE_DOMAIN_FILTER
        #  value: "dome-marketplace-dev.org"
        - name: LOG_LEVEL
          value: debug
        - name: IONOS_API_KEY
          valueFrom:
            secretKeyRef:
              name: ionos-token-secret
              key: token
        - name: SERVER_HOST
          value: "0.0.0.0" 
        - name: IONOS_DEBUG
          value: "true"  
