---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keyrock-secret
  namespace: dome-trust
spec:
  encryptedData:
    adminPassword: AgCT+zzkHU0x5itfihJ+l3KziAS3RMmc+QiH6iuj5kg3owSqushQLgnzzA8FFHOFYtxDe7GHdRGLSDaZGuFSh5w0q5hl6gHh0X48EjOTDIDvSFkd4vq1YmWfV2KO3t454cYwjVm6xtRLkRIptXMOwrQMoQrBCvlmvAsqItEsafW0mOytbWpMtl90oUgawBztpOjDT1qyHLA8uSw4VjjGKsML/CL66nPwO5+PMCHjqEfERxhz658fb3grrmaSRb87jj57VGMf9/tLjeAhxrcfCsrgKBxp/kQFCqw/Mf/V/36RvZESU2WnubT3f3TqfuZLxB7jwE9qiVbn5tyn4s/3WD0oXaJiCNX1kTPf+UvaJgCztuCBEdUDNxYIPYTpe2AJ48l71oCo4QlXD1NrooFhydg8SaWjyXLKTT4OLih0fdB20IKK1TCQf5LUZK9SnjAqiAvBxgdpVGTvvGJgyjbK9r29oAUFeOW8M2ylz42OMiCviwF+xdOmiKlY+C1SkDdsMgnjTkM08tSWsxHfg2Lo2LpV8ttwUYLfrnqlbUytWZvlbf6Ko31MNl3TYUwUzzSufwLaOE/ihlVnrmmZPqJDiJ8KNNn+Q6Xx0cr6xkg9SmZZzaP/QT4DMX0SF+5V6rHnxZpmqgiel2NalMovQw8uWTZWK8rmxuLxgVhzS+89luSkTOapyF3qqWfU+afO6pHBoFz9ZolXSMOdKfweszfVhq7I
    # same password defined in mysql-secret.mysql-root-password
    dbPassword: AgALV+XicgZWGWeuNHLk7dXUV9BapwJgSjmiot45e7FwgYwuEAcekW6CnXnpCvchIsn8iqt/+6kIgvhXMkrrbtiqAcCHkTSdIlyYNn/enhG9JW7q6M3Oe/KZbDNWDpE326HaxiT68+1vaqNnhmGgZFU4hq9FXLsIitu83PMP2Y6Z0VR2TJQpWxiev3Qr+1f3uk8BAgJqdWQCnLGlfrRg3GKXYrhsVVSxskidsNG0vVPjezQjuQSZFkgxTouFqHKsIHj//TaFXccbu0HjZ+fXAXEvXdKvdgNeHuypN2bqdpg0vP8LS916LJL+iRNZNz5Vncn4s3omThdRn+6fMXrfKcYgDtBbt+ygun247D7csgg7U3X2B6+lQdGMUac8H24EPkH42CfLCIEYr2qkVTQpWlhxCv0E1gFmzrsiz1K/Y5iQtbe7deiw1usCb+nTROPyAP8pa3TO+eMqhbIzEsKY/gwczk/0HE7ryq/llw/0I85kzVCbRnRjoTd2TC5ovIaOasE8DCuLF78VDsdvxVCzOxASIv3W3GngB+dJZJr7ajXHdjzLE+RbIUaSUpkXM+ez2Mffjh+aoeGc7NONUqVPJq3DGAogBNSotyEGujn4IH3sm0ziDhp/Ru4jEQM2Xe1Bkx6qeR5aXHvZMzOCxnkQaUbOGqDJ2dXd26SGF6yWeKqty0GSIJajXd85Zf39vUqyUBGgmAkf94Z7pJZmMjT90Miu
  template:
    metadata:
      creationTimestamp: null
      name: keyrock-secret
      namespace: dome-trust
