apiVersion: v2
name: trusted-registries
type: application
version: 1.0.0
dependencies:
  - name: portal
    version: 1.0.0
    repository: https://dome-marketplace.github.io/helm-charts/trust-framework
  - name: api
    version: 1.0.0
    repository: https://dome-marketplace.github.io/helm-charts/trust-framewok
