---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-secret
  namespace: marketplace
spec:
  encryptedData:
    keycloak-admin: AgCwFoX9tiY2DvnSjBB17Dy6L7LIvbF06/qiRieRAuGwmuWnyci+uXdd2V1CkAYm90hHe94Q23uKktX6uquK+l03oXVur7dHZkZ4g6XcfCvC5HTjusvRRCWKJPa+eNc9yWzTrdqA2UjT6emS56QP+0/DrJkscBjOeVMCiK1ajXj3fJair2IRhPhvI603LiUwKxe3bByYrfOTE6mxW0YSUZWmVarT+Rvjgxy26ZyEu7jjM/0/r05zWYKSn3sOnYDgGHg3T8oDrW6oQ5wx5xiZaISTNjSOPT0C0SPnX6ia0smTGVTQcJR6ZChwsEBsLlC8qMzDwJB5UCA2E4iJ6qNiCa3s1CiqV8bf44W0KGCJAVzse0ZZMu0mSnZIZg2dxJx+LEyiUpkQX9Bu9vvNVF5dgYNMxKFiMruzSN4qT2lRf5PTeSVbN773fP1aeigFb6SORden0TcNRLDVd6n6O5y6PYIsr5DIYuP0MA/eZDSy344J+Q7rRs1gDYZ3Z4TWbXc9Uj8QV2uyoON7izfS1hSkItdrmUbc/Ptaw4og73x1onR+qm0zwHbkst0mTIYPClWpJ8ldYC1SFz9GmBoBro+dIVx2dTDMd1gsnM8CjsUTOjcxJcEhjGcAAXTVdKMreOa+mzJp1J2DjymVR+pN54cGeIi13YmIg8cSLzaHq7TMNfSeJ+MGkQs7Ch7nGdLvnMOhfePevo0xL7GUi/c8fCKELckeUQ==
  template:
    metadata:
      creationTimestamp: null
      name: keycloak-secret
      namespace: marketplace
